# SwiftLint configuration for swift-iso-9899
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides
# Disable type_name validation because test suites use lowercase function names like "pow()", "sqrt()"
disabled_rules:
  - type_name
